---
# tasks file for firewall

- name: Disable Firewall Service
  service: name=ufw state=stopped enabled=False
  when: ansible_os_family == "Debian" 



- name: Disable Firewalld Service
  service: name=firewalld state=stopped enabled=False
  when: ansible_os_family == "Redhat" 
