---
# handlers file for webserver
- name: Restart Apache AV
  service: name=apache2 state=restarted
  when:  ansible_os_family == "Debian"
- name: amit
  shell: 'echo "Hello Handlers {{ansible_hostname}}" >> /tmp/handlers.txt'

