---

nginx: 
  image: nginx:latest
  ports: 
    - '8090:80'



myapache: 
  image: amitvashist7/devops-netmagic-08-aug-2022-myapache:v1
  ports: 
    - '8096:80'



myapache2: 
  image: amitvashist7/devops-netmagic-08-aug-2022-myapache:v5
  ports: 
    - '8092:80'
